pub const TRT_ERR_NAME: [&'static str; 8] = [
    "TRT_OK",
    "TRT_CREATE_ENGINE_FAIL",
    "TRT_CREATE_RUNTIME_FAIL",
    "TRT_CREATE_CONTEXT_FAIL",
    "TRT_READ_ENGINE_FILE_FAIL",
    "TRT_INFER_FAIL",
    "TRT_DESTROY_ENGINE_FAIL",
    "TRT_CREATE_CUDASTREAM_FAIL",
];
